import {
  Activity01Icon,
  Add01Icon,
  AiMagicIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowUpRight01Icon,
  Attachment01Icon,
  Baby01Icon,
  BellIcon,
  BookOpen01Icon,
  BubbleChatIcon,
  Calendar03Icon,
  Camera01Icon,
  Cancel01Icon,
  ChartBarLineIcon,
  CheckmarkCircle01Icon,
  Edit02Icon,
  FastWindIcon,
  Fire03Icon,
  HashtagIcon,
  HeartIcon,
  HelpCircleIcon,
  HistoryIcon,
  Home01Icon,
  InformationCircleIcon,
  Medicine01Icon,
  MilkBottleIcon,
  Moon02Icon,
  Orbit01Icon,
  PackageIcon,
  Search01Icon,
  SentIcon,
  Settings02Icon,
  Share01Icon,
  Shield01Icon,
  ShoppingBag01Icon,
  SparklesIcon,
  StarIcon,
  Sun03Icon,
  ThermometerIcon,
  TranslateIcon,
  UserCircleIcon,
  UserIcon,
  Wifi01Icon,
} from '@hugeicons/core-free-icons'
import type { IconSvgElement } from '@hugeicons/react'

/**
 * One semantic name per product action. Components consume these names instead
 * of importing an icon library directly, so every demo converges on one glyph.
 */
export const momcozyIcons = {
  activity: Activity01Icon,
  add: Add01Icon,
  ai: AiMagicIcon,
  arrowDown: ArrowDown01Icon,
  arrowLeft: ArrowLeft01Icon,
  arrowRight: ArrowRight01Icon,
  arrowUp: ArrowUp01Icon,
  attachment: Attachment01Icon,
  baby: Baby01Icon,
  book: BookOpen01Icon,
  calendar: Calendar03Icon,
  camera: Camera01Icon,
  chart: ChartBarLineIcon,
  check: CheckmarkCircle01Icon,
  close: Cancel01Icon,
  community: Orbit01Icon,
  device: PackageIcon,
  edit: Edit02Icon,
  featured: Fire03Icon,
  favorite: HeartIcon,
  help: HelpCircleIcon,
  history: HistoryIcon,
  home: Home01Icon,
  info: InformationCircleIcon,
  jump: ArrowUpRight01Icon,
  language: TranslateIcon,
  medicine: Medicine01Icon,
  message: BubbleChatIcon,
  notification: BellIcon,
  package: PackageIcon,
  profile: UserIcon,
  profileCircle: UserCircleIcon,
  pump: MilkBottleIcon,
  search: Search01Icon,
  send: SentIcon,
  settings: Settings02Icon,
  share: Share01Icon,
  shield: Shield01Icon,
  shoppingBag: ShoppingBag01Icon,
  sparkles: SparklesIcon,
  star: StarIcon,
  tag: HashtagIcon,
  themeMoon: Moon02Icon,
  themeSun: Sun03Icon,
  thermometer: ThermometerIcon,
  wifi: Wifi01Icon,
  wind: FastWindIcon,
} as const satisfies Record<string, IconSvgElement>

export type MomcozyIconName = keyof typeof momcozyIcons
